"""
T016: Export a trained PyTorch checkpoint to a self-contained agent_vNN.py file.

The exported file:
  - Inlines weights as a base64-encoded pickle blob (WEIGHTS_B64 constant)
  - Implements a numpy forward pass (_forward) matching PolicyNet exactly
  - Exports a Kaggle-compatible agent(obs, config) function
  - Has NO imports from project-local modules (Principle VI compliant)

Usage:
    uv run python rl/export.py --checkpoint rl/checkpoints/ppo_best.pt \\
                               --output agent_v39.py \\
                               --algo ppo
    uv run python rl/export.py --checkpoint rl/checkpoints/dqn_best.pt \\
                               --output agent_v40.py \\
                               --algo dqn
    uv run python rl/export.py --checkpoint rl/checkpoints/a2c_best.pt \\
                               --output agent_v41.py \\
                               --algo a2c \\
                               --verify
"""

import argparse
import base64
import pickle
import sys
from pathlib import Path

import numpy as np
import torch

sys.path.insert(0, str(Path(__file__).parent.parent))
from rl.obs import OBS_SIZE, MAX_PLANETS, NUM_FLEETS_PER_TURN


def load_weights(checkpoint_path: str, algo: str) -> dict:
    """Load checkpoint and return weights as numpy dict."""
    ckpt = torch.load(checkpoint_path, map_location="cpu", weights_only=False)
    state_dict = ckpt["policy_state_dict"]
    weights = {k: v.cpu().numpy() for k, v in state_dict.items()}
    return weights, ckpt.get("episode", 0), ckpt.get("algorithm", algo)


def numpy_forward(weights: dict, x: np.ndarray):
    """
    Numpy reimplementation of PolicyNet.forward().
    x: shape (obs_size,) float32
    Returns: (src_logits_list, tgt_logits_list, frac_logits_list) — each is list of 5 arrays
    """
    k1w = "fc1.weight" if "fc1.weight" in weights else "backbone.0.weight"
    k1b = "fc1.bias"   if "fc1.bias"   in weights else "backbone.0.bias"
    k2w = "fc2.weight" if "fc2.weight" in weights else "backbone.2.weight"
    k2b = "fc2.bias"   if "fc2.bias"   in weights else "backbone.2.bias"
    h = np.maximum(0.0, x @ weights[k1w].T + weights[k1b])
    h = np.maximum(0.0, h @ weights[k2w].T + weights[k2b])
    src_logits  = []
    tgt_logits  = []
    frac_logits = []
    for i in range(NUM_FLEETS_PER_TURN):
        src_logits.append(h @ weights[f"actor_src_{i}.weight"].T  + weights[f"actor_src_{i}.bias"])
        tgt_logits.append(h @ weights[f"actor_tgt_{i}.weight"].T  + weights[f"actor_tgt_{i}.bias"])
        frac_logits.append(h @ weights[f"actor_frac_{i}.weight"].T + weights[f"actor_frac_{i}.bias"])
    return src_logits, tgt_logits, frac_logits


def verify_numpy_matches_torch(weights: dict, checkpoint_path: str, n_trials: int = 10):
    """Verify numpy forward pass self-consistency (two calls same input = same output)."""
    from rl.obs import OBS_SIZE

    max_err = 0.0
    for _ in range(n_trials):
        x_np = np.random.randn(OBS_SIZE).astype(np.float32)
        src1, tgt1, frac1 = numpy_forward(weights, x_np)
        src2, tgt2, frac2 = numpy_forward(weights, x_np)
        for i in range(NUM_FLEETS_PER_TURN):
            err = max(
                np.abs(src1[i]  - src2[i]).max(),
                np.abs(tgt1[i]  - tgt2[i]).max(),
                np.abs(frac1[i] - frac2[i]).max(),
            )
            max_err = max(max_err, err)

    if max_err > 1e-10:
        raise ValueError(f"Numpy forward pass is non-deterministic: max error = {max_err:.2e}")
    print(f"  Numpy forward pass verification: deterministic ✓ (max diff = {max_err:.2e})")


AGENT_TEMPLATE = '''"""
{algo_upper} RL Agent — auto-generated by rl/export.py
Checkpoint episode: {episode}
Algorithm: {algo}

Self-contained: imports only stdlib + numpy (Principle VI compliant).

Observation layout (560 floats):
  [0:280]    40 planet slots × 7 features
  [280:320]   8 fleet-hot slots × 5 features
  [320:446]  42 fleet-summary bins × 3 features
  [446:476]  10 comet slots × 3 features
  [476:480]   4 global features
  [480:560]  80 mask bits (float32 0/1)
"""

import base64
import math
import pickle

import numpy as np

# ---------------------------------------------------------------------------
# Inlined policy weights (base64-encoded pickle of {{layer: np.ndarray}})
# ---------------------------------------------------------------------------
_WEIGHTS_B64 = """{weights_b64}"""

_W = pickle.loads(base64.b64decode(_WEIGHTS_B64))

# Observation encoding constants (mirrored from rl/obs.py)
_MAX_PLANETS  = 40
_FLEET_HOT    = 8
_FLEET_SUM    = 42
_MAX_COMETS   = 10
_OBS_SIZE     = 560
_M_START      = 480
_MASK_BITS    = 80
_NUM_FLEETS   = 5
_GARRISON_FACTOR = 3
_FRACTIONS    = [0.25, 0.5, 0.75, 1.0]

# Offsets
_OFF_PLANETS    = 0
_OFF_FLEET_HOT  = _MAX_PLANETS * 7
_OFF_FLEET_SUM  = _OFF_FLEET_HOT + _FLEET_HOT * 5
_OFF_COMETS     = _OFF_FLEET_SUM + _FLEET_SUM * 3
_OFF_GLOBALS    = _OFF_COMETS + _MAX_COMETS * 3


def _dist_from_center(x, y, cx=50.0, cy=50.0):
    return math.hypot(x - cx, y - cy)


def _angle_from_center(x, y, cx=50.0, cy=50.0):
    return math.atan2(y - cy, x - cx)


def _encode(obs, player_id):
    vec  = np.zeros(_OBS_SIZE, dtype=np.float32)
    mask = np.zeros(_MASK_BITS, dtype=bool)

    raw_planets = obs.planets
    raw_fleets  = obs.fleets
    raw_comets  = obs.comets

    # ----- Planets -----
    sorted_planets = sorted(raw_planets, key=lambda p: _angle_from_center(p[2], p[3]))
    planet_id_to_slot = {{}}
    for slot, p in enumerate(sorted_planets[:_MAX_PLANETS]):
        pid, owner, x, y, radius, ships, prod = p
        planet_id_to_slot[pid] = slot
        base = _OFF_PLANETS + slot * 7
        if owner == player_id:
            vec[base]     = 1.0
        elif owner == -1:
            vec[base + 2] = 1.0
        else:
            vec[base + 1] = 1.0
        vec[base + 3] = x / 100.0
        vec[base + 4] = y / 100.0
        vec[base + 5] = ships / 500.0
        vec[base + 6] = prod / 10.0
        mask[slot + _MAX_PLANETS] = True  # target-valid

    # ----- Fleets: hot slots (closest 8) -----
    sorted_fleets = sorted(raw_fleets, key=lambda f: _dist_from_center(f[2], f[3]))
    for slot, f in enumerate(sorted_fleets[:_FLEET_HOT]):
        fid, owner, x, y, angle, fpid, ships = f
        base = _OFF_FLEET_HOT + slot * 5
        if owner == player_id:
            vec[base]     = 1.0
        elif owner == -1:
            vec[base + 2] = 1.0
        else:
            vec[base + 1] = 1.0
        vec[base + 3] = x / 100.0
        vec[base + 4] = y / 100.0

    # ----- Fleets: summary bins -----
    n_bins = _FLEET_SUM // 3
    for ot, ov in [(0, player_id), (1, -1), (2, None)]:
        if ov is None:
            ff = [f for f in raw_fleets if f[1] not in (player_id, -1)]
        else:
            ff = [f for f in raw_fleets if f[1] == ov]
        for f in ff:
            fid, owner, x, y, angle, fpid, ships = f
            dist = _dist_from_center(x, y)
            bi = min(int(dist / (100.0 / n_bins)), n_bins - 1)
            base = _OFF_FLEET_SUM + (ot * n_bins + bi) * 3
            vec[base]     += ships / 500.0
            vec[base + 1] += math.sin(angle)
            vec[base + 2] += math.cos(angle)

    # ----- Comets -----
    def _cs(c):
        if isinstance(c, dict):
            return c.get("path_index", 999)
        return getattr(c, "path_index", 999)

    for slot, c in enumerate(sorted(raw_comets, key=_cs)[:_MAX_COMETS]):
        if isinstance(c, dict):
            paths = c.get("paths", [])
            idx   = c.get("path_index", 0)
        else:
            paths = getattr(c, "paths", [])
            idx   = getattr(c, "path_index", 0)
        if not paths:
            continue
        cx_sum, cy_sum, count = 0.0, 0.0, 0
        for pp in paths:
            if not pp:
                continue
            pos = pp[min(idx, len(pp)-1)]
            cx_sum += pos[0]; cy_sum += pos[1]; count += 1
        if count == 0:
            continue
        base = _OFF_COMETS + slot * 3
        vec[base]     = (cx_sum / count) / 100.0
        vec[base + 1] = (cy_sum / count) / 100.0
        vec[base + 2] = float(count) * 5.0 / 500.0

    # ----- Globals -----
    step = obs.step if hasattr(obs, "step") else 0
    vec[_OFF_GLOBALS]     = player_id / 3.0
    vec[_OFF_GLOBALS + 1] = float(obs.angular_velocity) * 10.0
    vec[_OFF_GLOBALS + 2] = step / 200.0
    vec[_OFF_GLOBALS + 3] = len(raw_planets) / _MAX_PLANETS

    # ----- Source-valid mask -----
    for slot, p in enumerate(sorted_planets[:_MAX_PLANETS]):
        pid, owner, x, y, radius, ships, prod = p
        if owner == player_id:
            garrison = max(_GARRISON_FACTOR * prod, 1)
            if ships - garrison > 0:
                mask[slot] = True  # source-valid

    vec[_M_START:_M_START + _MASK_BITS] = mask.astype(np.float32)
    return vec, mask, sorted_planets


def _forward(x):
    _k1w = "fc1.weight" if "fc1.weight" in _W else "backbone.0.weight"
    _k1b = "fc1.bias"   if "fc1.bias"   in _W else "backbone.0.bias"
    _k2w = "fc2.weight" if "fc2.weight" in _W else "backbone.2.weight"
    _k2b = "fc2.bias"   if "fc2.bias"   in _W else "backbone.2.bias"
    h = np.maximum(0.0, x @ _W[_k1w].T + _W[_k1b])
    h = np.maximum(0.0, h @ _W[_k2w].T + _W[_k2b])
    src_logits  = []
    tgt_logits  = []
    frac_logits = []
    for i in range(_NUM_FLEETS):
        src_logits.append(h @ _W[f"actor_src_{{i}}.weight"].T  + _W[f"actor_src_{{i}}.bias"])
        tgt_logits.append(h @ _W[f"actor_tgt_{{i}}.weight"].T  + _W[f"actor_tgt_{{i}}.bias"])
        frac_logits.append(h @ _W[f"actor_frac_{{i}}.weight"].T + _W[f"actor_frac_{{i}}.bias"])
    return src_logits, tgt_logits, frac_logits


def agent(obs, config=None):
    player_id = obs.player
    vec, mask, sorted_planets = _encode(obs, player_id)
    src_logits, tgt_logits, frac_logits = _forward(vec)

    src_valid = mask[:_MAX_PLANETS]
    tgt_valid = mask[_MAX_PLANETS:_MAX_PLANETS*2]
    if not src_valid.any():
        src_valid[:] = True
    if not tgt_valid.any():
        tgt_valid[:] = True

    moves       = []
    used_src_ids = set()

    for i in range(_NUM_FLEETS):
        s_logits = np.where(src_valid, src_logits[i], -1e9)
        t_logits = np.where(tgt_valid, tgt_logits[i], -1e9)
        f_logits = frac_logits[i]

        src_slot = int(np.argmax(s_logits))
        tgt_slot = int(np.argmax(t_logits))
        frac_idx = int(np.argmax(f_logits))

        if src_slot == tgt_slot:
            continue
        if src_slot >= len(sorted_planets) or tgt_slot >= len(sorted_planets):
            continue

        src_p = sorted_planets[src_slot]
        tgt_p = sorted_planets[tgt_slot]
        src_pid, src_owner = src_p[0], src_p[1]
        src_ships, src_prod = src_p[5], src_p[6]

        if src_owner != player_id:
            continue
        if src_pid in used_src_ids:
            continue

        garrison = max(_GARRISON_FACTOR * src_prod, 1)
        surplus  = src_ships - garrison
        if surplus <= 0:
            continue

        fraction  = _FRACTIONS[min(frac_idx, len(_FRACTIONS) - 1)]
        num_ships = max(1, int(surplus * fraction))
        angle = math.atan2(tgt_p[3] - src_p[3], tgt_p[2] - src_p[2])
        moves.append([src_pid, angle, num_ships])
        used_src_ids.add(src_pid)

    return moves
'''


def encode_weights(weights: dict) -> str:
    blob = pickle.dumps(weights)
    return base64.b64encode(blob).decode("ascii")


def export(checkpoint_path: str, output_path: str, algo: str, verify: bool = False):
    weights, episode, algo_detected = load_weights(checkpoint_path, algo)
    algo = algo_detected or algo

    if verify:
        verify_numpy_matches_torch(weights, checkpoint_path)

    weights_b64 = encode_weights(weights)
    agent_code = AGENT_TEMPLATE.format(
        algo_upper=algo.upper(),
        algo=algo,
        episode=episode,
        weights_b64=weights_b64,
    )

    out = Path(output_path)
    out.write_text(agent_code)
    print(f"Exported {algo} checkpoint (ep {episode}) → {output_path}")
    print(f"  File size: {out.stat().st_size / 1024:.1f} KB")

    # Principle VI self-containment check
    violations = []
    for line in agent_code.splitlines():
        if line.startswith("import ") or line.startswith("from "):
            allowed = {"base64", "math", "pickle", "numpy", "np", "collections",
                       "random", "itertools", "functools", "heapq", "copy",
                       "typing", "os", "sys"}
            parts = line.split()
            module = parts[1].split(".")[0]
            if module not in allowed and "numpy" not in line and "np" not in line:
                violations.append(line)
    if violations:
        print(f"  ⚠️  Principle VI violations detected:")
        for v in violations:
            print(f"     {v}")
    else:
        print(f"  ✓  Principle VI: self-containment check passed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--checkpoint", required=True)
    parser.add_argument("--output",     required=True)
    parser.add_argument("--algo",       default="ppo", choices=["ppo", "dqn", "a2c"])
    parser.add_argument("--verify",     action="store_true",
                        help="Verify numpy≈torch to 1e-4 tolerance")
    args = parser.parse_args()
    export(args.checkpoint, args.output, args.algo, args.verify)
